### ISSUE TITLE
Google's connection is down

### ISSUE THREAD

**Issue by SuperCarryFu** [jeromerony/augmented_lagrangian_adversarial_attacks#1]
Google's connection has been invalid, can you provide a new link?

**Comment by jeromerony** [comment]
Hi,
Thanks for pointing it out, sorry for that. Google Drive has reduced the quota for university accounts, so I cannot use that anymore.
I updated the link to OneDrive, but it is only a temporary solution. I will try to find a more permanent one.

**Comment by SuperCarryFu** [comment]
Thank  you, My English is not very good, please don't worry about grammar，Do you know baidu net disk? This may be a good choice

**Comment by jeromerony** [comment]
Like Google Drive or Microsoft OneDrive, Baidu will not offer a permanent solution.
